### ISSUE TITLE
Duplicating page content in the header on pages that use the "custom" header with TinyMCE

### ISSUE THREAD

**Issue by foodbandlt** [UCF/Athena-Shortcodes-Plugin#104]
**Describe the bug**
When using the "Custom" header content type, you get a TinyMCE editor that lets your format content differently.  When using this option with Athena Shortcodes enabled, even leaving the TinyMCE editor blank, the whole page is duplicated inside of the header area on the final page.   

In addition, we're not able to disable the TinyMCE editor support in this plugin's settings.  Every other settings updates correctly, the TinyMCE support checkbox just re-checks itself after saving. 

Example in QA: https://creolcmsqa.smca.ucf.edu/www/

**Steps to Reproduce**

1. Enable "custom" header content type on a page
2. Update page
3. Reload page, content is now duplicated in the header

**Expected Behavior**
The content of the TinyMCE editor should be reflected in the header.

**Possible Fix**

Perhaps something with how this handles TinyMCE?  We don't even necessarily need this plugin to work in the headers, but we're also unable to disable TinyMCE support in the settings page of this plugin.

**Your environment:**

 - OS: All
 - Browser & Version: Any
 - WordPress Version: 6.1.1
 - Plugin Version: 0.7.5

**Additional context**

**Comment by jmbarne3** [comment]
So, I've gone ahead and created a page using what you have in the header for the home page, but instead of using Elementor, I used the "classic" WordPress interface: https://creolcmsqa.smca.ucf.edu/www/home-classic/

Based on that outcome, I think the incompatibility is actually between our theme and Elementor, or possibly one of the other plugins installed on the site. One thing that I would recommend is to one by one, disable each plugin you have installed that might conflict (i.e. the ACF Quick Edit plugin, the Elementor plugin, Ultimate Add-ons for Elementor, Unlimited Elements for Elementor, etc.), test to see if the problem has gone away, and then reenabling the plugin before moving onto the next. If you discover which plugin is causing the problem, we can look into why it's happening and if there's something we can do on our end to correct the problem.

I don't think the TinyMCE plugin is necessarily the problem, so I'm hesitant to just add the disable logic and call it a day. This is based on the fact that the correct markup is present in the field, both in the database, and when you open the page in the editor, so the correct data is being written and read from the DB. It seems more likely to me that one of the plugins is interrupting the output of the `header` area of the page and starting to write the rest of the page before that section is done being output. This might be due to a filter or action that gets called during the process, so we may be able to adjust the priority of that filter or action to prevent the behavior.

Let me know what you discover and we will continue to look into this.

**Comment by foodbandlt** [comment]
Interesting interesting!  We'll look into this a little more and try to figure out where it's going wrong.

Just to clarify, that logic appears to already be present to disable support for shortcodes in TinyMCE?  Or perhaps it used to anyway, there's a checkbox on the settings page for this plugin with said option.  Saving changes after disabling it just re-checks the checkbox, not sure if that's intended or not.

Thanks for looking into this Jim!  We'll let you know if we figure anything else out with it.

**Comment by jmbarne3** [comment]
10-4, I will definitely check that out. I believe this is going to be a something that was added to the UCF-WordPress-Theme to force the setting, so would be a change to that theme, and not to this plugin. I'll take a look and report back. Thank you!

**Comment by jmbarne3** [comment]
Yes, [it appears we're forcing the setting for the plugin from within the theme code](https://github.com/UCF/UCF-WordPress-Theme/blob/d9caaf74b7a37720ddda583009e98c57260f44f4/includes/config.php#L321-L323). I think we can probably make this a default setting on theme activation, but not force it by default so that it can be disabled. I'll add an issue.

**Comment by jmbarne3** [comment]
[Issue opened](https://github.com/UCF/UCF-WordPress-Theme/issues/141)

**Comment by foodbandlt** [comment]
Hey again Jim!  We got around to trying your troubleshooting steps as you laid out above and found the only one that makes a difference is disabling Elementor itself.  This behavior is just very odd because the custom header field and TinyMCE editor work fine with Elementor without Athena Shortcodes enabled.   Super weird.

Thanks for submitting that other issue, appreciate it!

**Comment by jmbarne3** [comment]
@foodbandlt I've created a [branch on the UCF-WordPress-Theme](https://github.com/UCF/UCF-WordPress-Theme/tree/tinymce) that will allow that tinymce setting to be changed, but I still don't think it's going to effect the issue you're having. That setting is specific to the enqueuing of styles for the admin screen (so the visual editor has the athena styles, and not just the default WordPress style) so I don't think disabling that is going to have an effect on how the front end is behaving.

I have a little time to explore this today, so I'm going to see if I can track down an recreate your environment locally and take a look at what elementor is doing when it spits out the header area on the page. We'll see what we see!

**Comment by jmbarne3** [comment]
Resolved in [v0.7.8](https://github.com/UCF/Athena-Shortcodes-Plugin/releases/tag/v0.7.8). Instructions on where to disable the behavior can be found in the [wiki](https://github.com/UCF/Athena-Shortcodes-Plugin/wiki#elementor-settings).
